# Generated by Django 6.0.1 on 2026-02-03 08:07

import UserManager.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', UserManager.manager.UserManager()),
            ],
        ),
    ]
