# Generated by Django 6.0.1 on 2026-02-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='casino_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
