# Generated by Django 6.0.1 on 2026-02-03 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0003_account_casino_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='share_type',
            field=models.CharField(choices=[('CHANGE', 'CHANGE'), ('FIXED', 'FIXED')], default='FIXED', max_length=20),
        ),
    ]
