# Generated by Django 6.0.1 on 2026-02-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0004_account_share_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='coins',
            field=models.IntegerField(default=0),
        ),
    ]
