# Generated by Django 6.0.1 on 2026-02-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0007_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_enabled_by_parent',
            field=models.BooleanField(default=True),
        ),
    ]
