# Generated by Django 6.0.1 on 2026-02-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0008_account_is_enabled_by_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='reference',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
