# Generated by Django 6.0.1 on 2026-02-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0009_account_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='refrence_match_share',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
