# Generated by Django 6.0.1 on 2026-02-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0010_account_refrence_match_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='partnership_deed',
            field=models.JSONField(blank=True, default=list, help_text='Stores dynamic partnership values for the hierarchy of this account'),
        ),
    ]
